apiVersion: apps/v1
kind: Deployment
metadata:
  name: debit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debit-service
  template:
    metadata:
      labels:
        app: debit-service
    spec:
      containers:
      - name: debit-service
        image: your-container-registry/biro-debit-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: debit-service
spec:
  selector:
    app: debit-service
  ports:
  - port: 80
    targetPort: 80
