apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
      - name: transfer-service
        image: your-container-registry/biro-transfer-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-service
spec:
  selector:
    app: transfer-service
  ports:
  - port: 80
    targetPort: 80
